apiVersion: v1
kind: Pod
metadata:
  name: mongodb 
spec:
  nodeName: kind-worker
  volumes:
  - name: mongodb-data
    hostPath:
      path: /tmp/mongodb
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db


